//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalDetail
    {
        public int ID { get; set; }
        public Nullable<int> ApprovalID { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusComment { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Approval Approval { get; set; }
        public virtual Person Person { get; set; }
    }
}
