//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprisalParameters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApprisalParameters()
        {
            this.AppraiserForm = new HashSet<AppraiserForm>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Levels { get; set; }
        public string Parameter { get; set; }
        public Nullable<int> Weightage { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppraiserForm> AppraiserForm { get; set; }
    }
}
