//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalReporting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppraisalReporting()
        {
            this.ReviewerComment = new HashSet<ReviewerComment>();
        }
    
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int AppraiserID { get; set; }
        public int ReviewerID { get; set; }
        public Nullable<int> AppraiserRating { get; set; }
        public Nullable<int> ReviewerRating { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string ReviewerComments { get; set; }
        public string AppraiserComments { get; set; }
        public Nullable<bool> IsFreezed { get; set; }
        public string FreezedComments { get; set; }
        public Nullable<int> AppraiserYear { get; set; }
        public string EmpName { get; set; }
        public string AppraiserName { get; set; }
        public string ReviewerName { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Location { get; set; }
        public int LocationId { get; set; }
        public Nullable<bool> IsInitiat { get; set; }
        public Nullable<bool> IsEligible { get; set; }
        public string Designation { get; set; }
        public string OneToOneComment { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public string PromotionFor { get; set; }
        public Nullable<int> FinalReviewerRating { get; set; }
        public Nullable<int> DeliveryUnit { get; set; }
        public Nullable<int> DeliveyTeam { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> IsTrainingRequired { get; set; }
        public string TrainingFor { get; set; }
        public Nullable<decimal> AppraiserRatingBySystem { get; set; }
        public Nullable<decimal> ReviewerRatingBySystem { get; set; }
        public Nullable<bool> IsPromotionByRiviwer { get; set; }
        public string PromotionForByRiviwer { get; set; }
        public Nullable<bool> IsCriticalForOrganize { get; set; }
        public string CriticalForOrganizeFor { get; set; }
        public Nullable<bool> IsCriticalForProject { get; set; }
        public string CriticalForProject { get; set; }
        public Nullable<bool> IsPromotionNorm { get; set; }
        public string PromotionforByNorm { get; set; }
        public string OneToOneImprovementComment { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        public virtual Person Person3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewerComment> ReviewerComment { get; set; }
    }
}
