//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Approval()
        {
            this.ApprovalDetail = new HashSet<ApprovalDetail>();
            this.EmployeeProfileAttachment = new HashSet<EmployeeProfileAttachment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RequestBy { get; set; }
        public Nullable<int> RequestType { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> Component { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalDetail> ApprovalDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeProfileAttachment> EmployeeProfileAttachment { get; set; }
    }
}
