//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidatePersonal
    {
        public int ID { get; set; }
        public Nullable<int> HighestQualification { get; set; }
        public bool IsValidPassport { get; set; }
        public bool IsUSVisa { get; set; }
        public bool ReadytoRelocate { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public string SpouseName { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string AlternateContactNo { get; set; }
        public string PersonalEmail { get; set; }
        public string AlternateEmail { get; set; }
        public string Hobbies { get; set; }
        public int CandidateID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
