//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.CandidateAddress = new HashSet<CandidateAddress>();
            this.CandidateEmploymentHistory = new HashSet<CandidateEmploymentHistory>();
            this.CandidatePassport = new HashSet<CandidatePassport>();
            this.CandidatePersonal = new HashSet<CandidatePersonal>();
            this.CandidateQualificationMapping = new HashSet<CandidateQualificationMapping>();
            this.CandidateSkillMapping = new HashSet<CandidateSkillMapping>();
            this.CandidateCertification = new HashSet<CandidateCertification>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Salutation { get; set; }
        public int CandidateStatus { get; set; }
        public Nullable<int> SourceType { get; set; }
        public string SourceName { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
        public Nullable<int> ExperienceMonths { get; set; }
        public Nullable<int> ReleventExperienceYears { get; set; }
        public Nullable<int> ReleventExperienceMonths { get; set; }
        public Nullable<decimal> CurrentCTC { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Image { get; set; }
        public string ResumePath { get; set; }
        public string PanNumber { get; set; }
        public string PFNumber { get; set; }
        public string RRFNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateAddress> CandidateAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateEmploymentHistory> CandidateEmploymentHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatePassport> CandidatePassport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatePersonal> CandidatePersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateQualificationMapping> CandidateQualificationMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateSkillMapping> CandidateSkillMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateCertification> CandidateCertification { get; set; }
    }
}
