//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateEmploymentHistory
    {
        public int ID { get; set; }
        public string OrganisationName { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> WorkedTill { get; set; }
        public string EmploymentType { get; set; }
        public string LastDesignation { get; set; }
        public string RoleDescription { get; set; }
        public int CandidateID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
