//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSkillMapping
    {
        public int ID { get; set; }
        public int SkillID { get; set; }
        public int CandidateID { get; set; }
        public int ExperienceYears { get; set; }
        public Nullable<int> ExperienceMonths { get; set; }
        public bool HasCoreCompetency { get; set; }
        public int SkillRating { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual SkillMatrix SkillMatrix { get; set; }
    }
}
