//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAttachments
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public string ContractFileName { get; set; }
        public int AttachedBy { get; set; }
        public System.DateTime AttachedOn { get; set; }
    
        public virtual CustomerContract CustomerContract { get; set; }
    }
}
