//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosecData
    {
        public string UserID { get; set; }
        public System.DateTime PDate { get; set; }
        public Nullable<System.DateTime> Punch1 { get; set; }
        public Nullable<decimal> SPFID1 { get; set; }
        public Nullable<System.DateTime> Punch2 { get; set; }
        public Nullable<decimal> SPFID2 { get; set; }
        public Nullable<System.DateTime> Punch3 { get; set; }
        public Nullable<decimal> SPFID3 { get; set; }
        public Nullable<System.DateTime> Punch4 { get; set; }
        public Nullable<decimal> SPFID4 { get; set; }
        public Nullable<System.DateTime> Punch5 { get; set; }
        public Nullable<decimal> SPFID5 { get; set; }
        public Nullable<System.DateTime> Punch6 { get; set; }
        public Nullable<decimal> SPFID6 { get; set; }
        public string SchSFT { get; set; }
        public string SchSTAT { get; set; }
        public string WrkSFT { get; set; }
        public Nullable<decimal> EarlyIn { get; set; }
        public Nullable<decimal> LateIn { get; set; }
        public Nullable<decimal> EarlyOut { get; set; }
        public Nullable<decimal> Overstay { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> WorkTime { get; set; }
        public string DHalf1 { get; set; }
        public string DHalf2 { get; set; }
        public string RHalf1 { get; set; }
        public string RHalf2 { get; set; }
        public Nullable<decimal> MANOT { get; set; }
        public Nullable<decimal> AUTHOT { get; set; }
        public Nullable<System.DateTime> AUTHOTDate { get; set; }
        public Nullable<decimal> OTRID { get; set; }
        public Nullable<decimal> MANCOFF { get; set; }
        public Nullable<decimal> AUTHCOFF { get; set; }
        public Nullable<System.DateTime> AUTHCOFFDate { get; set; }
        public Nullable<decimal> AVLCOFF { get; set; }
        public Nullable<System.DateTime> AVLCOFFDate { get; set; }
        public Nullable<decimal> ENCCOFF { get; set; }
        public Nullable<System.DateTime> ENCCOFFDate { get; set; }
        public Nullable<decimal> LunchBreak { get; set; }
        public Nullable<decimal> LunchLate { get; set; }
        public Nullable<decimal> LunchEarly { get; set; }
        public Nullable<decimal> WOPHFlg { get; set; }
        public Nullable<decimal> OFCLTime { get; set; }
        public Nullable<decimal> PERSTime { get; set; }
        public Nullable<decimal> PERSCNT { get; set; }
        public Nullable<decimal> MANENT { get; set; }
        public Nullable<decimal> MANABS { get; set; }
        public Nullable<decimal> ATDAUTHFlg { get; set; }
        public Nullable<decimal> PERSAUTHflg { get; set; }
        public Nullable<decimal> OfficialAUTHflg { get; set; }
        public Nullable<decimal> ErrorID { get; set; }
        public Nullable<decimal> SFTALW { get; set; }
        public Nullable<decimal> WorkTimePaid { get; set; }
        public Nullable<decimal> TempWorkTime { get; set; }
        public Nullable<decimal> AuthOTPaid { get; set; }
        public Nullable<decimal> TempAuthOT { get; set; }
        public string RHalf1Paid { get; set; }
        public string TempRHalf1 { get; set; }
        public string RHalf2Paid { get; set; }
        public string TempRHalf2 { get; set; }
        public Nullable<decimal> SFTALWPaid { get; set; }
        public Nullable<decimal> TempSFTALW { get; set; }
        public Nullable<decimal> PREVADJFLG { get; set; }
        public Nullable<decimal> CloseFLG { get; set; }
        public Nullable<decimal> ORGID { get; set; }
        public Nullable<decimal> BRCID { get; set; }
        public Nullable<decimal> DPTID { get; set; }
        public Nullable<decimal> SECID { get; set; }
        public Nullable<decimal> CTGID { get; set; }
        public Nullable<decimal> GRDID { get; set; }
        public Nullable<decimal> DSGID { get; set; }
        public Nullable<decimal> LateInPLCID { get; set; }
        public Nullable<decimal> EarlyOutPLCID { get; set; }
        public Nullable<decimal> OTPLCID { get; set; }
        public Nullable<decimal> COFFPLCID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> OutPunch { get; set; }
        public Nullable<decimal> OutSPFID { get; set; }
        public Nullable<decimal> InGrace { get; set; }
        public Nullable<decimal> OutGrace { get; set; }
        public Nullable<decimal> LunchInGrace { get; set; }
        public Nullable<decimal> LunchOutGrace { get; set; }
        public string PersOffReason { get; set; }
        public Nullable<decimal> SiteID { get; set; }
        public Nullable<decimal> LateInCnt { get; set; }
        public Nullable<decimal> EarlyOutCnt { get; set; }
        public Nullable<decimal> DPTID1 { get; set; }
        public Nullable<decimal> DPTID2 { get; set; }
        public Nullable<decimal> DPTID3 { get; set; }
        public Nullable<System.DateTime> Punch7 { get; set; }
        public Nullable<decimal> SPFID7 { get; set; }
        public Nullable<System.DateTime> Punch8 { get; set; }
        public Nullable<decimal> SPFID8 { get; set; }
        public Nullable<System.DateTime> Punch9 { get; set; }
        public Nullable<decimal> SPFID9 { get; set; }
        public Nullable<System.DateTime> Punch10 { get; set; }
        public Nullable<decimal> SPFID10 { get; set; }
        public Nullable<System.DateTime> Punch11 { get; set; }
        public Nullable<decimal> SPFID11 { get; set; }
        public Nullable<System.DateTime> Punch12 { get; set; }
        public Nullable<decimal> SPFID12 { get; set; }
        public Nullable<System.DateTime> Punch1_AdjVal { get; set; }
        public Nullable<System.DateTime> OutPunch_AdjVal { get; set; }
        public Nullable<decimal> EarlyIn_AdjVal { get; set; }
        public Nullable<decimal> Overstay_AdjVal { get; set; }
        public Nullable<decimal> WorkTime_AdjVal { get; set; }
        public Nullable<decimal> Overtime_AdjVal { get; set; }
        public Nullable<decimal> RINId1 { get; set; }
        public Nullable<decimal> RINId2 { get; set; }
        public Nullable<decimal> RINId3 { get; set; }
        public Nullable<decimal> RINId4 { get; set; }
        public Nullable<decimal> RINId5 { get; set; }
        public Nullable<decimal> RINId6 { get; set; }
        public Nullable<decimal> ROUTId1 { get; set; }
        public Nullable<decimal> ROUTId2 { get; set; }
        public Nullable<decimal> ROUTId3 { get; set; }
        public Nullable<decimal> ROUTId4 { get; set; }
        public Nullable<decimal> ROUTId5 { get; set; }
        public Nullable<decimal> ROUTId6 { get; set; }
        public Nullable<decimal> ManSftChng { get; set; }
        public Nullable<decimal> OutTime { get; set; }
        public Nullable<decimal> Perstime1 { get; set; }
        public Nullable<decimal> Perstime2 { get; set; }
        public Nullable<decimal> Perstime3 { get; set; }
        public Nullable<decimal> Perstime4 { get; set; }
        public string AUTHBY { get; set; }
        public Nullable<decimal> AVLOT { get; set; }
        public Nullable<decimal> MANOTDB { get; set; }
        public Nullable<decimal> MANCOFFDB { get; set; }
        public string ManEntCorrBy { get; set; }
        public Nullable<System.DateTime> ManEntCorrDate { get; set; }
        public Nullable<decimal> AutoAdjOTHrs { get; set; }
        public Nullable<decimal> AutoLeaveFlg { get; set; }
        public Nullable<decimal> AutoOTFlg { get; set; }
        public Nullable<decimal> LessWrkHrs { get; set; }
        public Nullable<decimal> sftidtf { get; set; }
        public Nullable<decimal> NetWorkTime { get; set; }
        public Nullable<decimal> ShiftType { get; set; }
        public Nullable<decimal> IgnoreException { get; set; }
        public string AuthRemark { get; set; }
        public string PersOffRemark { get; set; }
        public Nullable<System.DateTime> lunchout { get; set; }
        public Nullable<decimal> lunchoutspfid { get; set; }
        public Nullable<decimal> lunchoutpos { get; set; }
        public Nullable<System.DateTime> lunchin { get; set; }
        public Nullable<decimal> lunchinspfid { get; set; }
        public Nullable<decimal> lunchinpos { get; set; }
        public Nullable<System.DateTime> OfficialAuthDate { get; set; }
        public string OfficialAuthBy { get; set; }
        public Nullable<decimal> OfficialAuthMode { get; set; }
        public string OfficialAuthEmail { get; set; }
        public Nullable<System.DateTime> PersAuthDate { get; set; }
        public string PersAuthBy { get; set; }
        public Nullable<decimal> PersAuthMode { get; set; }
        public string PersAuthEmail { get; set; }
        public Nullable<System.DateTime> ATDAuthDate { get; set; }
        public string ATDAuthBy { get; set; }
        public Nullable<decimal> perstimeunauth { get; set; }
        public Nullable<decimal> ofcltimeunauth { get; set; }
        public string CWMWOID { get; set; }
        public Nullable<decimal> AutoSrtLvFlg { get; set; }
        public Nullable<decimal> AutoOFCLFlg { get; set; }
        public Nullable<decimal> OTDailyWeeklyMonthly { get; set; }
        public Nullable<decimal> PERSCNT1 { get; set; }
        public Nullable<decimal> PERSCNT2 { get; set; }
        public Nullable<decimal> PERSCNT3 { get; set; }
        public Nullable<decimal> PERSCNT4 { get; set; }
    }
}
