//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContactPerson
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Type { get; set; }
        public string Designation { get; set; }
        public string Role { get; set; }
        public string Skype { get; set; }
        public string Email { get; set; }
        public string OfficeTelephone { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string FaxNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
