//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerList
    {
        public int Customer { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Phone { get; set; }
        public string FaxNumber { get; set; }
        public string EmailID { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNumber { get; set; }
        public string HomePhone { get; set; }
        public string Notes { get; set; }
        public string OnlineContact { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> TotalReceived { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public Nullable<int> CreditPeriod { get; set; }
        public Nullable<System.DateTime> ContractValidityDate { get; set; }
        public string ContractDocument { get; set; }
        public Nullable<double> SalesExpectedI { get; set; }
        public Nullable<double> SalesExpectedII { get; set; }
        public Nullable<double> SalesExpectedIII { get; set; }
        public Nullable<double> SalesExpectedIV { get; set; }
        public Nullable<int> LastInvoiceNumber { get; set; }
        public Nullable<int> BusinessType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ProfitCenterID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> AccountGroupID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string ProjectOrProductCustomer { get; set; }
        public string CustomFieldText1 { get; set; }
        public string CustomFieldText2 { get; set; }
        public string CustomFieldText3 { get; set; }
        public string CustomFieldText4 { get; set; }
        public string CustomFieldText5 { get; set; }
        public Nullable<double> CustomFieldNumeric1 { get; set; }
        public Nullable<double> CustomFieldNumeric2 { get; set; }
        public Nullable<double> CustomFieldNumeric3 { get; set; }
        public Nullable<double> CustomFieldNumeric4 { get; set; }
        public Nullable<double> CustomFieldNumeric5 { get; set; }
        public Nullable<System.DateTime> CustomFieldDate1 { get; set; }
        public Nullable<System.DateTime> CustomFieldDate2 { get; set; }
        public Nullable<System.DateTime> CustomFieldDate3 { get; set; }
        public Nullable<System.DateTime> CustomFieldDate4 { get; set; }
        public Nullable<System.DateTime> CustomFieldDate5 { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
