//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAction
    {
        public long ID { get; set; }
        public Nullable<System.Guid> AuthKey { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<bool> isAccessed { get; set; }
        public Nullable<System.DateTime> CreatredOn { get; set; }
        public Nullable<System.DateTime> ActionOn { get; set; }
        public string ActionID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
