//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public int TemplateId { get; set; }
        public string TemplateFor { get; set; }
        public string Html { get; set; }
        public string OptionalVariables { get; set; }
        public string Subjects { get; set; }
    }
}
