//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emails
    {
        public int Id { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public int TemplateType { get; set; }
        public bool IsSent { get; set; }
        public System.DateTime Date { get; set; }
        public string Content { get; set; }
        public string Subject { get; set; }
        public string EmailCC { get; set; }
        public string EmailAction { get; set; }
        public string Attachments { get; set; }
    }
}
