//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProfileAttachment
    {
        public int ID { get; set; }
        public int ApprovalID { get; set; }
        public string FieldName { get; set; }
        public string FileName { get; set; }
        public string UniqueFileName { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Approval Approval { get; set; }
    }
}
