//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExitFormEmployeeDeclaration
    {
        public int ID { get; set; }
        public Nullable<int> SeparationID { get; set; }
        public string Question1 { get; set; }
        public string Question1Comment { get; set; }
        public string Question2 { get; set; }
        public string Question2Comment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
