//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetails_New
    {
        public int ExpenseDetailId { get; set; }
        public Nullable<int> ExpenseId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ExpenseDate { get; set; }
        public Nullable<int> ExpenseCategoryId { get; set; }
        public string Comments { get; set; }
        public string AttachedFile { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Expense_New Expense_New { get; set; }
    }
}
