//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expense()
        {
            this.ExpenseDetails = new HashSet<ExpenseDetails>();
            this.ExpenseApprovalStage = new HashSet<ExpenseApprovalStage>();
        }
    
        public int ExpenseId { get; set; }
        public Nullable<int> IsClientReimbursment { get; set; }
        public Nullable<int> ClientName { get; set; }
        public Nullable<int> CostCenter { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string AmountInWords { get; set; }
        public string Comment { get; set; }
        public Nullable<int> StageID { get; set; }
        public string ReimbursementFormCode { get; set; }
        public string FormCode { get; set; }
        public string ChequeDetails { get; set; }
        public Nullable<int> PrimaryApprover { get; set; }
        public Nullable<int> SecondaryApprover { get; set; }
        public bool IsApproved { get; set; }
        public bool IsDraft { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string ReimbursementTitle { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseDetails> ExpenseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseApprovalStage> ExpenseApprovalStage { get; set; }
    }
}
