//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseApprovalStage
    {
        public int Id { get; set; }
        public Nullable<int> ExpenseID { get; set; }
        public Nullable<System.DateTime> EventDatatime { get; set; }
        public string Action { get; set; }
        public Nullable<int> FromStageId { get; set; }
        public Nullable<int> ToStageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Comments { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual Person Person { get; set; }
    }
}
