//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackForLeavingOrg
    {
        public int ID { get; set; }
        public Nullable<int> SeparationID { get; set; }
        public string FutherStudies { get; set; }
        public string FutherStudiesComment { get; set; }
        public string HealthFactor { get; set; }
        public string HealthFactorComment { get; set; }
        public string MarriageFamily { get; set; }
        public string MarriageFamilyComment { get; set; }
        public string OpportunitySalary { get; set; }
        public string OpportunitySalaryComment { get; set; }
        public string Overseas { get; set; }
        public string OverseasComment { get; set; }
        public string JobExpectation { get; set; }
        public string JobExpectationComment { get; set; }
        public string Work { get; set; }
        public string WorkComment { get; set; }
        public string WorkCulture { get; set; }
        public string WorkCultureComment { get; set; }
        public string WorkHours { get; set; }
        public string WorkHoursComment { get; set; }
        public string Responsibilities { get; set; }
        public string ResponsibilitiesComment { get; set; }
        public string TeamIssues { get; set; }
        public string TeamIssuesComment { get; set; }
        public string Recognition { get; set; }
        public string RecognitionComment { get; set; }
        public string ReportingHeadIssues { get; set; }
        public string ReportingHeadIssuesComment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
