//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int ID { get; set; }
        public string Location { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string Extension { get; set; }
        public string MimeType { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
