//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightDetails
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public bool IsDeleted { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> JourneyDate { get; set; }
        public Nullable<System.DateTime> ReturnJourneyDate { get; set; }

        public virtual Flight Flight { get; set; }
    }
}
