//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralPreferences
    {
        public int GeneralId { get; set; }
        public Nullable<bool> Iron { get; set; }
        public Nullable<bool> HairDryer { get; set; }
        public Nullable<bool> IronFacilites { get; set; }
        public Nullable<bool> General { get; set; }
    
        public virtual HotelBooking HotelBooking { get; set; }
    }
}
