//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpDeskCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HelpDeskCategories()
        {
            this.PersonHelpDesk = new HashSet<PersonHelpDesk>();
            this.HelpDeskSubCategories = new HashSet<HelpDeskSubCategories>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> AssignedRole { get; set; }
        public Nullable<int> AssignedExecutiveRole { get; set; }
        public string EmailGroup { get; set; }
        public string Prefix { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonHelpDesk> PersonHelpDesk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelpDeskSubCategories> HelpDeskSubCategories { get; set; }
    }
}
