//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpDeskSubCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HelpDeskSubCategories()
        {
            this.PersonHelpDesk = new HashSet<PersonHelpDesk>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public bool IsApprovalRequired { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonHelpDesk> PersonHelpDesk { get; set; }
        public virtual HelpDeskCategories HelpDeskCategories { get; set; }
    }
}
