//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayList
    {
        public int ID { get; set; }
        public Nullable<int> HolidayYear { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int HolidayType { get; set; }
        public string Description { get; set; }
        public Nullable<int> Location { get; set; }
        public bool IsDeleted { get; set; }
    }
}
