//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBooking
    {
        public int HotelId { get; set; }
        public int TravelId { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public int OccupancyType { get; set; }
        public string HotelName { get; set; }
        public string VendorName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string EmailId { get; set; }
        public string Comment { get; set; }
        public string TotalSummaryCost { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual GeneralPreferences GeneralPreferences { get; set; }
        public virtual Traveller Traveller { get; set; }
        public virtual KitchenPreferences KitchenPreferences { get; set; }
        public virtual MediaPreferences MediaPreferences { get; set; }
        public virtual ServicesPreferences ServicesPreferences { get; set; }
        public virtual InternetPreferences InternetPreferences { get; set; }
    }
}
