//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetPreferences
    {
        public int InternetId { get; set; }
        public Nullable<bool> Internet { get; set; }
        public Nullable<bool> FreeWiFi { get; set; }
        public Nullable<bool> PaidInternet { get; set; }
        public string Amount { get; set; }
    
        public virtual HotelBooking HotelBooking { get; set; }
    }
}
