//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobScheduler
    {
        public int SchedulerId { get; set; }
        public string SchedulerType { get; set; }
        public System.DateTime SchedulerDate { get; set; }
        public bool StatusType { get; set; }
    }
}
