//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitchenPreferences
    {
        public int KitchenId { get; set; }
        public Nullable<bool> CoffeeMachine { get; set; }
        public Nullable<bool> Microwave { get; set; }
        public Nullable<bool> Refridgerator { get; set; }
        public Nullable<bool> Utensils { get; set; }
        public Nullable<bool> Kitchen { get; set; }
    
        public virtual HotelBooking HotelBooking { get; set; }
    }
}
