//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRAFileUpload
    {
        public int Id { get; set; }
        public int KRAId { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public Nullable<System.DateTime> FileUploadedOn { get; set; }
        public Nullable<System.DateTime> FileDeletedOn { get; set; }
        public Nullable<int> FileUploadedBy { get; set; }
        public Nullable<int> FileDeletedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int KRAGoalId { get; set; }
    }
}
