//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationLeaf
    {
        public int ID { get; set; }
        public int WorkLocationID { get; set; }
        public Nullable<bool> IsLeaveApplicable { get; set; }
        public Nullable<bool> IsCLApplicable { get; set; }
        public Nullable<bool> IsSLApplicable { get; set; }
        public Nullable<bool> IsSFHApplicable { get; set; }
        public Nullable<bool> IsMLApplicable { get; set; }
        public Nullable<bool> IsPLApplicable { get; set; }
    
        public virtual WorkLocation WorkLocation { get; set; }
    }
}
