//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaPreferences
    {
        public int MediaId { get; set; }
        public Nullable<bool> FlatTV { get; set; }
        public Nullable<bool> CableChannels { get; set; }
        public Nullable<bool> Telephone { get; set; }
        public Nullable<bool> Fax { get; set; }
        public Nullable<bool> Media { get; set; }
    
        public virtual HotelBooking HotelBooking { get; set; }
    }
}
