//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleExtension
    {
        public int ModuleID { get; set; }
        public Nullable<bool> MackerChecker { get; set; }
        public string Roles { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
