//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Navigation()
        {
            this.RoleEntitlement = new HashSet<RoleEntitlement>();
        }
    
        public int ID { get; set; }
        public string Navigation1 { get; set; }
        public string Components { get; set; }
        public Nullable<bool> Action { get; set; }
        public Nullable<bool> OnMenu { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleEntitlement> RoleEntitlement { get; set; }
    }
}
