//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
	using System;
	using System.Collections.Generic;

	public partial class PersonKRA
	{
		public int KRAInitiationId { get; set; }
		public int PersonId { get; set; }
		public int KRAYearId { get; set; }
		public bool Q1 { get; set; }
		public bool Q2 { get; set; }
		public bool Q3 { get; set; }
		public bool Q4 { get; set; }
		public int ReviewerPersonId { get; set; }
		public System.DateTime FirstKRAInitiatedOn { get; set; }
		public System.DateTime FirstKRAInitiationStartDate { get; set; }
		public System.DateTime FirstKRAInitiationEndDate { get; set; }
		public int FirstKRAInitiatedBy { get; set; }
		public System.DateTime FirstKRAInitiationFreezedDate { get; set; }
		public int FirstKRAInitiationFreezedBy { get; set; }
		public bool IsFirstKRAInitiationFreezed { get; set; }
		public System.DateTime SecondKRAInitiatedOn { get; set; }
		public System.DateTime SecondKRAInitiationStartDate { get; set; }
		public System.DateTime SecondKRAInitiationEndDate { get; set; }
		public int SecondKRAInitiatedBy { get; set; }
		public System.DateTime SecondKRAInitiationFreezedDate { get; set; }
		public int SecondKRAInitiationFreezedBy { get; set; }
		public bool IsSecondKRAInitiationFreezed { get; set; }
		public System.DateTime ThirdKRAInitiatedOn { get; set; }
		public System.DateTime ThirdKRAInitiationStartDate { get; set; }
		public System.DateTime ThirdKRAInitiationEndDate { get; set; }
		public int ThirdKRAInitiatedBy { get; set; }
		public System.DateTime ThirdKRAInitiationFreezedDate { get; set; }
		public int ThirdKRAInitiationFreezedBy { get; set; }
		public bool IsThirdKRAInitiationFreezed { get; set; }
		public System.DateTime FourthKRAInitiatedOn { get; set; }
		public System.DateTime FourthKRAInitiationStartDate { get; set; }
		public System.DateTime FourthKRAInitiationEndDate { get; set; }
		public int FourthKRAInitiatedBy { get; set; }
		public System.DateTime FourthKRAInitiationFreezedDate { get; set; }
		public int FourthKRAInitiationFreezedBy { get; set; }
		public bool IsFourthKRAInitiationFreezed { get; set; }
		public int FirstKRAInitiationPercentageCompletion { get; set; }
		public int SecondKRAInitiationPercentageCompletion { get; set; }
		public int ThirdKRAInitiationPercentageCompletion { get; set; }
		public int FourthKRAInitiationPercentageCompletion { get; set; }
		public int OverAllYearlyPercentageCompletion { get; set; }
		public int Q1InitiatedFor { get; set; }
		public int Q2InitiatedFor { get; set; }
		public int Q3InitiatedFor { get; set; }
		public int Q4InitiatiedFor { get; set; }
		public virtual Person Person { get; set; }
		public virtual PersonKRAYear PersonKRAYear { get; set; }
	}
}
