//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEmploymentChangeLog
    {
        public int ID { get; set; }
        public int PersonEmploymentID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> ProbationMonths { get; set; }
        public Nullable<System.DateTime> ProbationReviewDate { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<System.DateTime> SeparationRequestDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string OrganizationEmail { get; set; }
        public Nullable<bool> RejoinedWithinYear { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<int> EmploymentStatus { get; set; }
        public string UserName { get; set; }
        public string BusinessGroup { get; set; }
        public string OrgUnit { get; set; }
        public Nullable<int> DeliveryUnit { get; set; }
        public Nullable<int> CurrentDU { get; set; }
        public Nullable<int> DeliveryTeam { get; set; }
        public Nullable<int> ResourcePool { get; set; }
        public string Commitment { get; set; }
        public string OfficeExtension { get; set; }
        public string SeatingLocation { get; set; }
        public Nullable<int> OfficeLocation { get; set; }
        public Nullable<int> WorkLocation { get; set; }
        public Nullable<int> CompetencyManager { get; set; }
        public Nullable<int> ExitProcessManager { get; set; }
        public bool IsDeleted { get; set; }
        public string TimeZone { get; set; }
        public Nullable<System.DateTime> EmploymentStatusDate { get; set; }
        public Nullable<bool> IsDayShift { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string RRFNumber { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> CompetencyID { get; set; }
        public string SkillDescription { get; set; }
    }
}
