//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;

    public partial class PersonKRAFeedback
    {
        public int ID { get; set; }
        public int KRAGoalId { get; set; }
        public int PersonId { get; set; }
        public int Year { get; set; }
        public string Quarter { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public bool IsDeleted { get; set; }

        public virtual PersonKRADetail PersonKRADetail { get; set; }
    }
}