//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonExitProcessForm
    {
        public int ID { get; set; }
        public Nullable<int> SeparationID { get; set; }
        public Nullable<int> FeedbackForLeavingOrg { get; set; }
        public string FeedbackForLeavingOrgRemark { get; set; }
        public Nullable<int> RatingForReportingLead { get; set; }
        public string RatingForReportingLeadRemark { get; set; }
        public Nullable<int> RatingForOrganization { get; set; }
        public string RatingForOrganizationRemark { get; set; }
        public Nullable<int> OrganizationDevelopmentSuggestion { get; set; }
        public string OrgDevelopmentSuggestionRemark { get; set; }
        public Nullable<int> EmployeeDeclaration { get; set; }
        public string EmployeeDeclarationRemark { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsHRReviewDone { get; set; }
    }
}
