//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBondDetail
    {
        public int ID { get; set; }
        public Nullable<long> BondAmount { get; set; }
        public Nullable<int> BondType { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> BondCompletionDate { get; set; }
        public int PersonID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
