//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSLCredit
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int CreditBalance { get; set; }
        public int CreditedBy { get; set; }
        public string Narration { get; set; }
        public int Year { get; set; }
        public System.DateTime DateEffective { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
