//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCertification
    {
        public int ID { get; set; }
        public Nullable<int> CertificationID { get; set; }
        public int PersonID { get; set; }
        public Nullable<System.DateTime> CertificationDate { get; set; }
        public string CertificationNumber { get; set; }
        public string Grade { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Certifications Certifications { get; set; }
        public virtual Person Person { get; set; }
    }
}
