//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonHelpDesk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonHelpDesk()
        {
            this.HelpDeskComments = new HashSet<HelpDeskComments>();
        }
    
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int CategoryID { get; set; }
        public int SubCategoryID { get; set; }
        public int Type { get; set; }
        public int Severity { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public bool IsApprovalRequired { get; set; }
        public int Status { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> AssignToRole { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> RequiredCompletionDate { get; set; }
        public Nullable<System.DateTime> PokedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelpDeskComments> HelpDeskComments { get; set; }
        public virtual HelpDeskSubCategories HelpDeskSubCategories { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual HelpDeskCategories HelpDeskCategories { get; set; }
    }
}
