//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDeclaration
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string RelationType { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> V2PersonID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
