//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonConfirmation
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> InitiatedDate { get; set; }
        public Nullable<int> ReportingManagerId { get; set; }
        public string ReportingManager { get; set; }
        public string TrainingFeedback { get; set; }
        public string BehaviourFeedback { get; set; }
        public string OverallFeedback { get; set; }
        public Nullable<int> ConfirmationState { get; set; }
        public Nullable<int> ExtendedTill { get; set; }
        public Nullable<int> PIPTill { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<bool> IsHRReviewDone { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
