//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPersonal
    {
        public string BloodGroup { get; set; }
        public string MaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> SpouseBirthDate { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string PANNo { get; set; }
        public string PFNo { get; set; }
        public string ESICNo { get; set; }
        public string PersonalEmail { get; set; }
        public string Hobbies { get; set; }
        public Nullable<int> NoofChildren { get; set; }
        public string Achievement { get; set; }
        public string PhotoFileName { get; set; }
        public string PhotoFilePath { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string AlternateEmail { get; set; }
        public string AlternateContactNo { get; set; }
        public string VOIPNo { get; set; }
        public string GtalkID { get; set; }
        public string SkypeID { get; set; }
        public string YIMID { get; set; }
        public int PersonID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
