//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDependent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonDependent()
        {
            this.PersonPassport = new HashSet<PersonPassport>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Relation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int PersonID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonPassport> PersonPassport { get; set; }
    }
}
