//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonKRAMapping
    {
        public int ID { get; set; }
        public int PersonId { get; set; }
        public int ParentKRAInitiationId { get; set; }
        public bool Q1 { get; set; }
        public bool Q2 { get; set; }
        public bool Q3 { get; set; }
        public bool Q4 { get; set; }
        public int InitiatedFor { get; set; }
        public bool IsParent { get; set; }
        public int KRAInitiationYear { get; set; }
    }
}
