//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonLeave
    {
        public int ID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> Leaves { get; set; }
        public Nullable<int> LWP { get; set; }
        public string Narration { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> NotConsumed { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
