//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonKRAHistoryDetail
    {
        public int Id { get; set; }
        public int KRAId { get; set; }
        public int KRACategoryId { get; set; }
        public int PersonId { get; set; }
        public string KRA { get; set; }
        public int YearId { get; set; }
        public string Description { get; set; }
        public int Weightage { get; set; }
        public bool IsManagerEdit { get; set; }
        public bool IsEmployeeEdit { get; set; }
        public bool IsDelete { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsCloned { get; set; }
        public int ParentKRAId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool IsKRADone { get; set; }
        public Nullable<System.DateTime> KRADoneOn { get; set; }
        public Nullable<bool> Q1 { get; set; }
        public Nullable<bool> Q2 { get; set; }
        public Nullable<bool> Q3 { get; set; }
        public Nullable<bool> Q4 { get; set; }
        public Nullable<int> KRAInitiationId { get; set; }
        public bool IsValid { get; set; }
        public string Comments { get; set; }
        public int KRAPercentageCompletion { get; set; }
        public Nullable<System.DateTime> KRAStartDate { get; set; }
        public Nullable<System.DateTime> KRAEndDate { get; set; }
        public bool IsKRAQuarterCompleted { get; set; }
        public bool IsKRAIntitiationCompleted { get; set; }
        public Nullable<System.DateTime> KRAInitiationEndDate { get; set; }
        public bool IsKRAAvailableForClone { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> KRAHistoryInsertedDate { get; set; }
        public Nullable<System.DateTime> KRAHistoryUpdatedOn { get; set; }
        public int KRAHistoryUpdatedBy { get; set; }
        public int KRAGoalId { get; set; }
    }
}
