//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonLeaveLedger
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> OpeningBalance { get; set; }
        public Nullable<int> LeaveUtilized { get; set; }
        public Nullable<int> CompOffs { get; set; }
        public Nullable<int> CompOffUtilized { get; set; }
        public Nullable<int> CLUtilized { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SLUtilized { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
