//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class phdbckup
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int CategoryID { get; set; }
        public int SubCategoryID { get; set; }
        public int Type { get; set; }
        public int Severity { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public bool IsApprovalRequired { get; set; }
        public int Status { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> AssignToRole { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> RequiredCompletionDate { get; set; }
        public Nullable<System.DateTime> PokedDate { get; set; }
    }
}
