//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSAllocationRatings
    {
        public int ID { get; set; }
        public Nullable<int> Technical { get; set; }
        public Nullable<int> Process { get; set; }
        public Nullable<int> Discipline { get; set; }
        public Nullable<int> Communication { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> Timelines { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int ReleaseRequestID { get; set; }
        public int AllocationID { get; set; }
    }
}
