//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSAllocationRequestDetailsHistory
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public int Percentage { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int BillableType { get; set; }
        public int ProjectRole { get; set; }
        public int ReportingTo { get; set; }
        public string Description { get; set; }
        public int RequestDetailsID { get; set; }
        public int Status { get; set; }
        public string RMGCOmments { get; set; }
        public System.DateTime StatusDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
