//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSAllocationRequest
    {
        public int RequestID { get; set; }
        public int ProjectID { get; set; }
        public int RequestedBy { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int Status { get; set; }
        public int RequestType { get; set; }
        public System.DateTime StatusDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<bool> IsActionPerformed { get; set; }
        public Nullable<int> PMSResourceAllocationId { get; set; }
    }
}
