//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSAllocationUpdateRequest
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> BillableType { get; set; }
        public Nullable<int> ProjectRole { get; set; }
        public Nullable<int> ReportingTo { get; set; }
        public string Comments { get; set; }
        public int RequestID { get; set; }
        public int Status { get; set; }
        public string RMGComments { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    }
}
