//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSInvoiceDetails
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BillableRsrc { get; set; }
        public string Description { get; set; }
        public string SOW_Reference { get; set; }
        public string AttachedFile { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
    
        public virtual PMSInvoice PMSInvoice { get; set; }
    }
}
