//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSResourceAllocation
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int ProjectID { get; set; }
        public int percentage { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int ProjectRole { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int ReportingTo { get; set; }
        public int BillbleType { get; set; }
        public int ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int BGStatus { get; set; }
    }
}
