//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSTimesheet
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public string Description { get; set; }
        public int ProjectID { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string JsonString { get; set; }
        public string Time { get; set; }
        public Nullable<int> SubProjectID { get; set; }
        public Nullable<int> SubTaskId { get; set; }
        public string TicketID { get; set; }
        public string NonBillableDescription { get; set; }
        public string NonBillableTime { get; set; }
        public string UploadType { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PMSTaskTypes PMSTaskTypes { get; set; }
        public virtual ProjectList ProjectList { get; set; }
    }
}
