//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSTaskAssignedMap
    {
        public int TaskId { get; set; }
        public int AssignedTo { get; set; }
        public System.DateTime AssignedDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PMSTasks PMSTasks { get; set; }
    }
}
