//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSTasks
    {
        public int ID { get; set; }
        public string SrNo { get; set; }
        public string TaskName { get; set; }
        public string FeatureType { get; set; }
        public string Description { get; set; }
        public string DefaultFields { get; set; }
        public string Acceptance { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string Hours { get; set; }
        public string Status { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual ProjectList ProjectList { get; set; }
    }
}
