//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectList()
        {
            this.PMSTasks = new HashSet<PMSTasks>();
            this.ProjectList1 = new HashSet<ProjectList>();
            this.PMSTimesheet = new HashSet<PMSTimesheet>();
        }
    
        public int ID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProjectManager { get; set; }
        public Nullable<int> DeliveryManager { get; set; }
        public System.DateTime ActualStartDate { get; set; }
        public System.DateTime ActualEndDate { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<bool> Billable { get; set; }
        public Nullable<int> DeliveryUnit { get; set; }
        public Nullable<int> DeliveryTeam { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public Nullable<bool> IsOffshore { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ParentProjId { get; set; }
        public string ProjectMethodology { get; set; }
        public string Process { get; set; }
        public string SprintDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSTasks> PMSTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectList> ProjectList1 { get; set; }
        public virtual ProjectList ProjectList2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSTimesheet> PMSTimesheet { get; set; }
    }
}
