//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Qualification()
        {
            this.CandidateQualificationMapping = new HashSet<CandidateQualificationMapping>();
            this.PersonQualificationMappings = new HashSet<PersonQualificationMapping>();
        }
    
        public int ID { get; set; }
        public string QualificationName { get; set; }
        public Nullable<int> QualificationGroupID { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateQualificationMapping> CandidateQualificationMapping { get; set; }
        public virtual QualificationGroup QualificationGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonQualificationMapping> PersonQualificationMappings { get; set; }
    }
}
