//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingForReportingLead
    {
        public int ID { get; set; }
        public Nullable<int> SeparationID { get; set; }
        public string CommunicationExpectation { get; set; }
        public string CommunicationExpectationComment { get; set; }
        public string ResolvedComplaints { get; set; }
        public string ResolvedComplaintsComment { get; set; }
        public string Teamwork { get; set; }
        public string TeamworkComment { get; set; }
        public string Approachable { get; set; }
        public string ApproachableComment { get; set; }
        public string Receptive { get; set; }
        public string ReceptiveComment { get; set; }
        public string TechnicalGuidance { get; set; }
        public string TechnicalGuidanceComment { get; set; }
        public string DevelopedYou { get; set; }
        public string DevelopedYouComment { get; set; }
        public string PerformanceFeedback { get; set; }
        public string PerformanceFeedbackComment { get; set; }
        public string Accomplishments { get; set; }
        public string AccomplishmentsComment { get; set; }
        public string Assignments { get; set; }
        public string AssignmentsComment { get; set; }
        public string EffectiveLeader { get; set; }
        public string EffectiveLeaderComment { get; set; }
        public string SensitiveToEmployee { get; set; }
        public string SensitiveToEmployeeComment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
