//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingForOrganization
    {
        public int ID { get; set; }
        public Nullable<int> SeparationID { get; set; }
        public string BenefitsAndPay { get; set; }
        public string BenefitsAndPayComment { get; set; }
        public string TrainingSessions { get; set; }
        public string TrainingSessionsComment { get; set; }
        public string OrgReviewSystem { get; set; }
        public string OrgReviewSystemComment { get; set; }
        public string OpenDoorPolicy { get; set; }
        public string OpenDoorPolicyComment { get; set; }
        public string JobPayment { get; set; }
        public string JobPaymentComment { get; set; }
        public string CareerOpportunity { get; set; }
        public string CareerOpportunityComment { get; set; }
        public string WorkingConditions { get; set; }
        public string WorkingConditionsComment { get; set; }
        public string OrganizationGrowth { get; set; }
        public string OrganizationGrowthComment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
