//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDropDownConfig
    {
        public decimal ID { get; set; }
        public decimal PersonId { get; set; }
        public decimal ModuleId { get; set; }
        public int ProjectIds { get; set; }
    }
}
