//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportMaster()
        {
            this.ReportAccessConfigs = new HashSet<ReportAccessConfig>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentReportID { get; set; }
        public string RedirectionText { get; set; }
        public string Description { get; set; }
        public string RouteUrl { get; set; }
        public string ImageUrl { get; set; }
        public string SelectedReportText { get; set; }
        public string ReportHeaderText { get; set; }
        public Nullable<bool> DefaultToAll { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportAccessConfig> ReportAccessConfigs { get; set; }
    }
}
