//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewerComment
    {
        public int Id { get; set; }
        public int AppraisalReportingId { get; set; }
        public int OrgCategoryId { get; set; }
        public string OrgCategoryDescription { get; set; }    
        public virtual AppraisalReporting AppraisalReporting { get; set; }
    }
}
