//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RRF()
        {
            this.RRFCandidate = new HashSet<RRFCandidate>();
            this.RRFComments = new HashSet<RRFComments>();
            this.RRFDetail = new HashSet<RRFDetail>();
            this.RRFSkill = new HashSet<RRFSkill>();
        }
    
        public int ID { get; set; }
        public string RRFNumber { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public int Positions { get; set; }
        public int SkillCategory { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public int Designation { get; set; }
        public int RequestedBy { get; set; }
        public Nullable<int> RRFStatus { get; set; }
        public Nullable<int> IsBifercate { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<bool> IsReplacement { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<decimal> Budget { get; set; }
    
        public virtual Designation Designation1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual ResourcePool ResourcePool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RRFCandidate> RRFCandidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RRFComments> RRFComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RRFDetail> RRFDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RRFSkill> RRFSkill { get; set; }
    }
}
