//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRFCandidate
    {
        public int ID { get; set; }
        public int RRFId { get; set; }
        public string CandidateSource { get; set; }
        public Nullable<int> EmployeeCode { get; set; }
        public Nullable<int> ReplacementFor { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> CandidiateStage { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual RRF RRF { get; set; }
    }
}
