//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRFComments
    {
        public int ID { get; set; }
        public int RRFId { get; set; }
        public int RRFStage { get; set; }
        public string Comments { get; set; }
        public System.DateTime CommentedDate { get; set; }
        public int CommentBy { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual RRF RRF { get; set; }
    }
}
