//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRFDetail
    {
        public int ID { get; set; }
        public int RRFId { get; set; }
        public int DeliveryTeam { get; set; }
        public int DeliveryUnit { get; set; }
        public Nullable<int> Project { get; set; }
        public string BusinessJustification { get; set; }
        public int ReportingTo { get; set; }
        public string BillabilityStatus { get; set; }
        public bool ApprovalStatus { get; set; }
        public int ApprovedBy { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> EmploymentType { get; set; }
        public Nullable<decimal> Budget { get; set; }
    
        public virtual DeliveryTeam DeliveryTeam1 { get; set; }
        public virtual DeliveryUnit DeliveryUnit1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual Project Project1 { get; set; }
        public virtual RRF RRF { get; set; }
    }
}
