//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRFSkill
    {
        public int ID { get; set; }
        public int RRFId { get; set; }
        public int SkillId { get; set; }
        public int Rating { get; set; }
    
        public virtual SkillMatrix SkillMatrix { get; set; }
        public virtual RRF RRF { get; set; }
    }
}
