//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Separation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Separation()
        {
            this.SeperationProcess = new HashSet<SeperationProcess>();
        }
    
        public int ID { get; set; }
        public System.DateTime ResignDate { get; set; }
        public System.DateTime ExpectedDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string SeperationReason { get; set; }
        public string Comments { get; set; }
        public int ApprovalID { get; set; }
        public int StatusID { get; set; }
        public int PersonID { get; set; }
        public string RejectRemark { get; set; }
        public string WithdrawRemark { get; set; }
        public Nullable<int> IsTermination { get; set; }
        public string TerminationRemark { get; set; }
        public Nullable<int> TerminationReason { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string AttachedFile { get; set; }
        public string ExitDateRemark { get; set; }
        public int NoticePeriod { get; set; }
        public int OldEmploymentStatus { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeperationProcess> SeperationProcess { get; set; }
    }
}
