//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesPreferences
    {
        public int ServiceId { get; set; }
        public Nullable<bool> AtmOnSIte { get; set; }
        public Nullable<bool> Laundry { get; set; }
        public Nullable<bool> ShoppingCenter { get; set; }
        public Nullable<bool> PickUpDrop { get; set; }
        public Nullable<bool> Services { get; set; }
    
        public virtual HotelBooking HotelBooking { get; set; }
    }
}
