//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignInSignOut
    {
        public long SignInSignOutID { get; set; }
        public Nullable<System.DateTime> SignInTime { get; set; }
        public Nullable<System.DateTime> SignOutTime { get; set; }
        public string TotalHoursWorked { get; set; }
        public Nullable<bool> IsSignInManual { get; set; }
        public Nullable<bool> IsSignOutManual { get; set; }
        public string SignInComment { get; set; }
        public string SignOutComment { get; set; }
        public Nullable<System.DateTime> ReportingTime { get; set; }
        public Nullable<int> statusID { get; set; }
        public long UserID { get; set; }
        public bool IsBulk { get; set; }
        public string WorkflowID { get; set; }
        public Nullable<long> ApproverID { get; set; }
        public string ApproverComments { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<System.DateTime> FirstModified { get; set; }
        public string DayNotation { get; set; }
        public string TimeZoneName { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
    }
}
