//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public int ID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string ModuleCode { get; set; }
        public Nullable<int> By { get; set; }
        public string PreviousEntry { get; set; }
        public string NewEntry { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ApprovalStatus { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> RecordID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
