//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARRFDetail
    {
        public int Id { get; set; }
        public int RRFNo { get; set; }
        public int Status { get; set; }
        public string comments { get; set; }
        public int RRFNumber { get; set; }
    }
}
