//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExtensionHistory
    {
        public int Id { get; set; }
        public int TravelDetailId { get; set; }
        public System.DateTime Departure { get; set; }
        public System.DateTime Arrival { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Visa { get; set; }
        public Nullable<System.DateTime> I94 { get; set; }
    
        public virtual TravelDetails TravelDetails { get; set; }
    }
}
