//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelDetails()
        {
            this.TravelExtensionHistory = new HashSet<TravelExtensionHistory>();
        }
    
        public int TravelId { get; set; }
        public int TravelType { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.DateTime JourneyDate { get; set; }
        public System.DateTime ReturnJourneyDate { get; set; }
        public Nullable<int> TripType { get; set; }
        public Nullable<bool> Accommodation { get; set; }
        public Nullable<DateTime> CheckInDate { get; set; }
        public Nullable<DateTime> CheckOutDate { get; set; }
        public Nullable<int> ReportingManagerId { get; set; }
        public Nullable<int> ExitManagerId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> RequestType { get; set; }
    
        public virtual Traveller Traveller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExtensionHistory> TravelExtensionHistory { get; set; }
    }
}
