//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelTransactions
    {
        public int Id { get; set; }
        public int TravelId { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> CardReloaded { get; set; }
        public Nullable<int> TravelCardType { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Traveller Traveller { get; set; }
    }
}
