//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelMoneyTransactions
    {
        public int Id { get; set; }
        public string Comments { get; set; }
        public int TravelId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CurrencyGivenDays { get; set; }
        public string ForexCardName { get; set; }
        public string CurrencygiveninCash { get; set; }
        public string CurrencyloadedinForexCard { get; set; }
        public string VendorName { get; set; }
        public string TotalCurrencyCost { get; set; }
        public Nullable<int> CurrencyType { get; set; }
    
        public virtual Traveller Traveller { get; set; }
    }
}
