//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCFApprover
    {
        public int id { get; set; }
        public long DeliveryUnitID { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
