//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPIdeaDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VPIdeaDetail()
        {
            this.VPReviewerDetails = new HashSet<VPReviewerDetail>();
            this.VPComments = new HashSet<VPComment>();
        }
    
        public long ID { get; set; }
        public string IdeaHeadline { get; set; }
        public string IdeaDescription { get; set; }
        public string IdeaBenefits { get; set; }
        public string RequiredEffort { get; set; }
        public string RequiredResources { get; set; }
        public string RequiredTechnologies { get; set; }
        public int SubmittedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string ExecutionApproach { get; set; }
        public bool IsEmailReceiptRequired { get; set; }
        public short StatusID { get; set; }
        public short PriorityID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<double> Target { get; set; }
        public Nullable<double> UniquenessQuotient { get; set; }
        public string TeammemberIds { get; set; }
        public string IsLockedBy { get; set; }
    
        public virtual VPPriority VPPriority { get; set; }
        public virtual VPStatu VPStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VPReviewerDetail> VPReviewerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VPComment> VPComments { get; set; }
    }
}
