//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pheonix.Web.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEmployment
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<System.DateTime> SeparationDate { get; set; }
        public string OfficialEmail { get; set; }
        public string PersonalEmail { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
