//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PhoenixEntities : DbContext
{
    public PhoenixEntities()
        : base("name=PhoenixEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<PersonSkillMapping> PersonSkillMappings { get; set; }
    public virtual DbSet<SkillMatrix> SkillMatrices { get; set; }
    public virtual DbSet<Person> People { get; set; }
    public virtual DbSet<PersonEmployment> PersonEmployments { get; set; }
}
