//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValuePortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ValuePortalEntities : DbContext
    {
        public ValuePortalEntities()
            : base("name=ValuePortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VPPriority> VPPriorities { get; set; }
        public virtual DbSet<VPReviewerDetail> VPReviewerDetails { get; set; }
        public virtual DbSet<VPStatu> VPStatus { get; set; }
        public virtual DbSet<VPComment> VPComments { get; set; }
        public virtual DbSet<VPBenefit> VPBenefits { get; set; }
        public virtual DbSet<VPCost> VPCosts { get; set; }
        public virtual DbSet<VPConfiguration> VPConfigurations { get; set; }
        public virtual DbSet<VPBenefitScope> VPBenefitScopes { get; set; }
        public virtual DbSet<VPIdeaDetail> VPIdeaDetails { get; set; }
    }
}
