//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValuePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPComment
    {
        public int id { get; set; }
        public long VPIdeaDetailID { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public string ReviewerComments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual VPIdeaDetail VPIdeaDetail { get; set; }
    }
}
