//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValuePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPReviewerDetail
    {
        public long ID { get; set; }
        public long VPIdeaDetailID { get; set; }
        public string ReviewerComments { get; set; }
        public string ReviewerComments2 { get; set; }
        public string ReviewerComments3 { get; set; }
        public Nullable<double> BenefitScore { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> FinalScore { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual VPIdeaDetail VPIdeaDetail { get; set; }
    }
}
